# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the MicroBuild template
pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - README.md
    - docs/*
trigger:
  batch: true
  branches:
    include:
    - main
variables:
- template: /eng/common/templates-official/variables/pool-providers.yml@self
- name: _TeamName
  value: Roslyn
- name: TeamName
  value: Roslyn
- name: _BuildConfig
  value: Release
- name: _SignType
  value: real

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022-pt
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enableMicrobuild: true
          enablePublishBuildArtifacts: true
          enablePublishTestResults: true
          enablePublishBuildAssets: true
          enablePublishUsingPipelines: true
          enableTelemetry: true
          enableSourceBuild: true
          helixRepo: dotnet/symreader
          jobs:
          - job: Windows
            pool:
              name: $(DncEngInternalBuildPool)
              image: 1es-windows-2022-pt
              os: windows
            variables:
              - group: Publish-Build-Assets
              - name: _OfficialBuildArgs
                value: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName) /p:DotNetPublishUsingPipelines=true /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
            steps:
            - checkout: self
              clean: true
            - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_OfficialBuildArgs)
              displayName: Build and Test

          - job: MacOS
            displayName: 'MacOS'
            pool:
              name: Azure Pipelines
              image: 'macOS-latest'
              os: macos
            steps:
            - checkout: self
              clean: true
            - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
              displayName: Build and Test

          - job: Linux
            displayName: 'Linux'
            pool:
              name: $(DncEngInternalBuildPool)
              image: 1es-mariner-2-pt
              os: linux
            steps:
            - checkout: self
              clean: true
            - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
              displayName: Build and Test

    - template: /eng/common/templates-official/post-build/post-build.yml@self
      parameters:
        publishingInfraVersion: 3
        enableSymbolValidation: false